### PR TITLE
[WIP] Create templates in Twig.templates object

### PR DESCRIPTION
**Pull request by adeslade**
Hi,

I'd like to get some feedback on this and also see what happens with the build (it does pass locally.)

Cheers

### CODE REVIEW

**Comment by adeslade** [comment]
Bah, build failed :disappointed:. I've been testing this version with our codebase and it's working nicely.

**Comment by hnrysmth** [comment]
I'm sad that CI didn't like this. It turned out that getting made redundant didn't lead to quite as much free time as I was hoping so I've not really been able to dive into the reason why it didn't run. Plus I've admittedly been being a bit lazy and making the most of the downtime :innocent: 

One possibility did occur to me though. These new automated integration tests are lovely in that they test *so* many things instantly and let us make big changes with confidence. But if there's one or two weird edge cases where they don't help, because of a false negative like this one, then maybe the pragmatic thing to do is just live without one of those tests for this bit of functionality?

What do you think? Would the build be green without `include_variable_template_name.test`?

**Comment by adeslade** [comment]
No worries, totally understandable. Congrats on your new role too, best of luck with that.

I'm not sure about removing that test, it seems pretty necessary. Must admit we have our own fork of this project again with the changes in and it's working out well. Did bust AMD compilation but fixed it with this interesting... [commit](https://github.com/basekit/twig.js/commit/49b7b8f25c7c8f00e4292f1809f5b32413487ac1).

Do you think it's worth creating a new PR with the changes to contribute back to the project?

**Comment by hnrysmth** [comment]
Nice. That commit does take care of all the painful little bookkeeping that I figured we'd need to have in place for this to work right. And the fact that it's *actually running* in probably the most battle-hardened production deploy of Twig.js out there is a very big stamp of approval. Also, it looks like that awkward test is running fine in BK's branch, which is good news too.

I reckon throw a PR over with those two commits in it. Let's see what Travis CI makes of it. If it's green I think we should just get this merged and do a major version bump.

**Pull request closed without merging**
