### PR TITLE
Update location of plovr + added php 5.4

### PR DESCRIPTION
**Pull request by oleg-andreyev**
- Updated location of plovr, because old URL was returning 404
- Added PHP 5.4

### CODE REVIEW

**Comment by oleg-andreyev** [comment]
@hensmith please take a look

**Comment by henrycatalinismith** [comment]
😇 sorry @oleg-andreyev dude im [no longer maintaining this](https://github.com/schmittjoh/twig.js/pull/120#issuecomment-453748027)! dont even have commit access any more! good luck!

**Comment by oleg-andreyev** [comment]
@hensmith understand your decision! sorry for bothering.

**Comment by oleg-andreyev** [comment]
ping @schmittjoh

**Pull request closed without merging**
