### PR TITLE
Get node logic ex

### LINKED ISSUE #107: [LogicException] Node "parent" does not exist for Node "Twig_Node_Module".
Since the update of Twig in Version 1.25.0 (2016-09-21), this error occurs at compile time :

```
[Twig_Error_Syntax]                                                          
  An exception has been thrown during the compilation of a template ("Node "p  
  arent" does not exist for Node "Twig_Node_Module".") in "my_view.html.twig".

[LogicException]                                           
  Node "parent" does not exist for Node "Twig_Node_Module".
```

Although "my_view.twig.html" is void of any twig code ...

### PR DESCRIPTION
**Pull request by DerManoMann**
Another PR to fix #107 plus some bonus deprecation fixes for the future.

Notes:
* ideally I'd like to drop composer.lock as it is considered bad style to include that in libraries
* I've fixed the supported versions of twig to 1.25 - 1.30.0 as master (1.30.1) does break
* However, I've included a few minor BC changes to get around most deprecation warnings...

### CODE REVIEW

**Comment by DerManoMann** [comment]
Might have got a bit carried away with the changes not related to the getNode() issue. If you prefer I can split this into individual ones...
Personally, I can think of at least 3:
* getNode() fixed for #107 
* remove composer.lock
* update composer.json with prefer-stable: true
* another PR after those to follow interface changes on twig dev-master

**Comment by hnrysmth** [comment]
Hmm yeah the composer.lock thing looks like a great thing to get rid of but you're right, belongs in its own PR. Same deal with composer.json I guess. Basically yeah, PRs that do one thing each are way way way easier to merge!

**Comment by hnrysmth** [comment]
BTW I appreciate how patient you've been on this stuff. Trying my best to continue to devote some time to this lovely little repo ❤️

**Comment by DerManoMann** [comment]
Progress! I'll try to get the actual issue isolated into a new PR - ironically, I might not get to that until 2 weeks from now - its summer in New Zealand ;)

**Comment by hnrysmth** [comment]
Hell yeah, get out and enjoy that summer!

**Comment by DerManoMann** [comment]
Closed in favour of #112, #113, #114 (and counting...)

**Pull request closed without merging**
