### PR TITLE
Libraries should not include a composer.lock file

### PR DESCRIPTION
**Pull request by DerManoMann**
Remving composer.lock as that is bad style for a library

### CODE REVIEW

**Comment by DerManoMann** [comment]
Will fail until #112 is merged

**Comment by hnrysmth** [comment]
Gaaaahh, ironic that a `composer.lock` merge conflict is now disabling the merge button on this 😆

**Comment by DerManoMann** [comment]
rebased :)

**Comment by hnrysmth** [comment]
nice 👌

**Pull request merged**
