### PR TITLE
Fix for #119

### PR DESCRIPTION
**Pull request by jstuhli**
Like #112 this PR adds checks for getNode method call and fixes the issue #119

### CODE REVIEW

**Comment by jstuhli** [comment]
@hnrysmth Any chance to get this merged? It's just 2 more checks on top of already merged #112, and all tests pass.

**Comment by ngodfraind** [comment]
Any news on this ?

**Comment by jstuhli** [comment]
@hensmith could this be merged? It would be great if I could remove my forked repository from composer.json. We have this running in production year and a half with no issues.
The last push is a change to avoid a warning on PHP 7.2

**Comment by henrycatalinismith** [comment]
Done! It's in as [`1.0.4`](https://github.com/schmittjoh/twig.js/tree/1.0.4) now! Haven't tested it at all cos the commit looks fine, and also cos I know how it feels to run a personal fork in production for a long time like this and then struggle to get it merged upstream!

Bit amazed to find I've managed to ignore a PR for two entire years 😆 TBH I think maybe it's time I stepped away from this project in a more official sense. It's now been something like four years since I last used this library myself, and I'm clearly way too disconnected from it to maintain it properly.

screenshot 2019-01-12 at 14 26 24

So I guess I'm gonna hit `I understand, leave this repository` after I post this comment! Have absolutely loved helping take care of this thing. Fingers crossed that actually officially ending my involvement will make maintenance expectations more clear, and so either attract new maintainers or encourage folks to migrate their stuff away if it turns out that literally nobody has the bandwidth to look after it any more.

Thanks everyone! ❤️

(Specially you Johannes! Might not have seemed like much to you at the time dude, but getting to help look after twig.js meant a lot to me back in the day!)

**Pull request merged**
